name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.9'

    - name: Start Kafka & Zookeeper
      run: |
        docker compose -f docker-compose.yml up -d
        echo "Waiting for Kafka and Zookeeper to be ready..."
        sleep 20

    - name: Verify Kafka containers
      run: docker ps -a

    - name: Run Go tests
      run: go test ./...
