name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'
  DOCKER_COMPOSE_VERSION: 'v2.26.1'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/compose-cli-action@v3
      with:
        version: ${{ env.DOCKER_COMPOSE_VERSION }}

    - name: Install dependencies
      run: go mod tidy

    - name: Start Kafka with Docker Compose
      run: |
        docker compose up -d
        echo "Waiting for Kafka to be ready..."
        while ! docker compose exec kafka kafka-topics --list --bootstrap-server localhost:9092 >/dev/null 2>&1; do
          sleep 2
        done
        echo "Kafka is ready!"

    - name: Run tests
      run: make test

    - name: Build binaries
      run: make build

    - name: Clean up
      if: always()
      run: docker compose down -v